### ISSUE TITLE
Base file

### ISSUE THREAD

**Issue by HugoGiraudel** [marcohamersma/nebula.css#4]
It is generally considered best practice to keep only imports (`@import` rules) in the main Sass file (`styles.scss` in this project).  I would recommend moving the CSS content from the main file into another one that gets imported in `styles.css` so it could look like this:

```scss
/**
 *  Nebula CSS Framework
 *  Designed & Developed by Marco Hamersma
 */

// Edit this file for setting up Nebula
@import 'nebula/config';

// This import runs nebula and adds helper classes according to the configuration
@import 'nebula/base';

// This is where you can add your site-specific styles
@import 'nebula/custom';
```

**Comment by marcohamersma** [comment]
Good to know. I'm trying to redefine how one includes Nebula in their project, which will probably result in this file being restructured/moved anyway. I'll address this then.
